export const ADD_MOVIE_TO_WATCHLIST = "ADD_MOVIE_TO_WATCHLIST";
export const Remove_MOVIE_FROM_WATCHLIST = "Remove_MOVIE_FROM_WATCHLIST";
export const ADD_MOVIE_TO_WATCHED = "ADD_MOVIE_TO_WATCHED";
export const Remove_MOVIE_FROM_WATCHED = "Remove_MOVIE_FROM_WATCHED";
export const MOVE_TO_WATCHED = "Move_TO_WATCHED";
